default_platform(:android)

platform :android do
  desc "Lane  for Android App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:234940025637:android:d1ec3ac270da408e6868cc",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"], 
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk" , 
      testers: ["esoodawood186@gmail.com", "adelyasmeen198@gmail.com"],
      release_notes: "Third Firebase Fastlane App Distribution"
    )
  end
end
