default_platform(:android)

platform :android do
  desc "Lane  for Android App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:234940025637:android:d1ec3ac270da408e6868cc",
      firebase_cli_token:  "1//03v1fPJa0kM99CgYIARAAGAMSNwF-L9IrEMmVQbBa2qNDXl-SrLBuuTxuVaD2YHEeDd2ctabVhqPjgl1M_6-O7x0Wco7OvWjhNbE", 
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk" , 
      testers: "esoodawood186@gmail.com",
      release_notes: "First Firebase Fastlane App Distribution"
    )
  end
end
